---
- name: Sonarqube installation
  hosts: localhost
  tasks: 
  - name: Run Sonarqube container
    command: docker run -d -p 9000:9000 --name sonarqube -v sonarqube_conf:/opt/sonarqube/conf -v sonarqube_extensions:/opt/sonarqube/extensions -v sonarqube_logs:/opt/sonarqube/logs -v sonarqube_data:/opt/sonarqube/data sonarqube
  
  - name: Adding firewall rule 8085,8086
    ufw:
      rule: allow
      port: 9000
      proto: tcp
